services:

  db:
    container_name: db
    image: postgres:15
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    env_file:
      - .env
    networks:
      - porsafzar_sharif_network

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: always
    env_file:
      - .env
    ports:
      - "5050:80"
    depends_on:
      - db
    networks:
      - porsafzar_sharif_network

  
  redis:
    container_name: redis
    image: redis:7-alpine
    restart: always
    networks:
      - porsafzar_sharif_network
  

  api:
    build:
      context: .
      dockerfile: ./docker/local/django/Dockerfile
    image: porsafzar_sharif
    container_name: api
    restart: always
    env_file:
      - .env
    volumes:
      - .:/src
    ports:
      - "8000:8000"
    command: /start.sh
    depends_on:
      
      - redis
      
      - db
    networks:
      - porsafzar_sharif_network

  
  worker:
    image: porsafzar_sharif
    container_name: worker
    restart: always
    env_file:
      - .env
    volumes:
      - .:/src
    command: /worker.sh
    depends_on:
      - redis
      - db
    networks:
      - porsafzar_sharif_network

  flower:
    image: porsafzar_sharif
    container_name: flower
    env_file:
      - .env
    volumes:
      - .:/src
    command: /flower.sh
    ports:
      - "5555:5555"
    depends_on:
      - redis
      - db
    networks:
      - porsafzar_sharif_network
  
  
  
  beat:
    image: porsafzar_sharif
    container_name: beat
    env_file:
      - .env
    volumes:
      - .:/src
    command: /beat.sh
    depends_on:
      - redis
      - db
      - api
    networks:
      - porsafzar_sharif_network
  

  smtp4dev:
    image: rnwood/smtp4dev
    container_name: smtp4dev
    restart: always
    ports:
      - "5000:80"
      - "2525:25"
      - "110:110"
    networks:
      - porsafzar_sharif_network

networks:
  porsafzar_sharif_network:
    driver: bridge

volumes:
  db_data:
